---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogd-apiserver
  namespace: catalogd-system
  labels:
    api: catalogd
    apiserver: "true"
spec:
  selector:
    matchLabels:
      api: catalogd
      apiserver: "true"
  replicas: 1
  template:
    metadata:
      labels:
        api: catalogd
        apiserver: "true"
    spec:
      containers:
      - name: apiserver
        image: quay.io/operator-framework/catalogd:latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: apiserver-certs
          mountPath: /apiserver.local.config/certificates
          readOnly: true
        command:
        - "./apiserver"
        args:
        - "--etcd-servers=http://etcd-svc:2379"
        - "--tls-cert-file=/apiserver.local.config/certificates/tls.crt"
        - "--tls-private-key-file=/apiserver.local.config/certificates/tls.key"
        - "--audit-log-path=-"
        - "--feature-gates=APIPriorityAndFairness=false"
        - "--audit-log-maxage=0"
        - "--audit-log-maxbackup=0"
        - "--profiling"
        resources:
          requests:
            cpu: 100m
            memory: 20Mi
          limits:
            cpu: 100m
            memory: 30Mi
      volumes:
      - name: apiserver-certs
        secret:
          secretName: catalogd
---
apiVersion: v1
kind: Service
metadata:
  name: catalogd
  namespace: catalogd-system
  labels:
    api: catalogd
    apiserver: "true"
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  selector:
    api: catalogd
    apiserver: "true"
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
    api: catalogd
    apiserver: "true"
  name: selfsigned-issuer
  namespace: catalogd-system
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    api: catalogd
    apiserver: "true"
  name: catalogd-cert
  namespace: catalogd-system
spec:
  dnsNames:
  - catalogd.catalogd-system.svc
  - catalogd.catalogd-system.svc.cluster.local
  - localhost
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: catalogd
