---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rukpak-packageserver-controller
  namespace: rukpak
  labels:
    api: rukpak-packageserver
    controller: "true"
spec:
  selector:
    matchLabels:
      api: rukpak-packageserver
      controller: "true"
  replicas: 1
  template:
    metadata:
      labels:
        api: rukpak-packageserver
        controller: "true"
    spec:
      securityContext:
        runAsUser: 0
      containers:
      - name: controller
        image: docker.io/anik120/catalogsource-controller:latest
        imagePullPolicy: IfNotPresent
        command:
        - "./manager"
        args:
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 100m
            memory: 300Mi
      volumes:
      - name: apiserver-certs
        secret:
          secretName: rukpak-packageserver
