---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogd-controller
  namespace: catalogd-system
  labels:
    api: catalogd
    controller: "true"
spec:
  selector:
    matchLabels:
      api: catalogd
      controller: "true"
  replicas: 1
  template:
    metadata:
      labels:
        api: catalogd
        controller: "true"
    spec:
      containers:
      - name: controller
        image: quay.io/operator-framework/catalogd-controller:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        command:
        - "./manager"
        args:
        # If you are interested in enabling the endpoints for collecting
        # performance metrics via pprof uncomment the below line:
        # - --profiling=true
        resources:
          requests:
            cpu: 1000m
            memory: 200Mi
          limits:
            cpu: 1000m
            memory: 300Mi
      volumes:
      - name: apiserver-certs
        secret:
          secretName: catalogd
